#+TITLE:  造纸白泥滤料的供碱释钙特性研究
#+SUBTITLE:  造纸白泥滤料的供碱释钙特性研究
#+AUTHOR: 陈力
#+options: top:nil
#+DATE:
#+options: toc:nil
#+latex_header: \usepackage{float}
#+latex_header:\usepackage{indentfirst}
#+latex_header:\setlength{\parindent}{2.0cm}
#+latex_header: \usepackage[utf8]{inputenc}
#+latex_header:\usepackage[T1]{fontenc}
#+latex_header:\usepackage{lipsum}
#+latex_header:\usepackage{mwe}
#+latex_header:\usepackage{lmodern}
#+latex_header:\usepackage{graphicx}
#+latex_header:\usepackage{caption}
#+latex_header:\usepackage{floatrow}

#+latex_header: \usepackage[super,square,comma,sort&compress]{natbib}
#+LATEX_HEADER: \usepackage[UTF8]{ctex}


----------------------
\begin{abstract}


白泥是一种在造纸工艺中生产出来的固体废物, 现在已经成为严重环境污染的来源之一. 本实验的目的是探究造纸白泥的供碱释钙特性的研究. 钙和氢氧根的释放主要来自于钙长石, 钙黄长石和以氧化钙(而非碳酸钙)形式存在的石灰, 并且钙黄长石的供碱释钙能力远比钙长石强. 在不同条件下, 如投加量, 孔结构(其主要影响因素为钙/硅比), 制得的陶粒的供碱释钙性能也不同

{{\it keywords:} 硅酸钙水合物; 磷回收; 多孔结构; 制备; pH值; 钙长石; 钙黄长石; }}

\end{abstract}
----------------------

* 简介
造纸白泥是造纸工业碱回收时经苛化反应形成的副产物，[6]其主要成分为碳酸钙，但由于高碱性和含有重金属元素，[8]其被定义为工业有毒有害物质。平均1吨的纸浆可以产生0.5吨的造纸白泥，[1]并且中国在2011年的造纸白泥产量已经接近1000万吨。[2]随着近年来对纸制品的需求，白泥量还在不断增长中。国内外的一些大型造纸厂(如佳木斯、吉林、青州造纸厂)均是采用石灰窑煅烧法，使造纸白泥再生生产石灰在苛化中循环使用。但是，造纸白泥的煅烧必须采用高质量的重油等优质原料，能耗较高，煅烧工艺和操作控制也相对比较复杂。另外，国内的造纸企业大都使用麦草、芦苇等非木质原料，得到的造纸白泥中硅元素含量高。若采用煅烧石灰的方法进行回收利用时，造纸白泥中的杂质硅易与碱金属氧化物形成水玻璃物质，造成物料胶粘，无法分离，多次循环后会严重影响碱回收效率和设备寿命。因此，大多数造纸厂选择直接将白泥填埋或堆放，这不仅污染环境、浪费资源，造纸厂还需要支付相应的排污费用。[3] 因此，造纸白泥的综合利用就成为我国甚至是世界造纸企业的亟待解决的问题。

本研究的目的是评估由石灰泥和粉煤灰制备的陶粒中Ca2 +和OH-释放的效率。 在批量实验
的基础上，研究了配方，用量，初始pH和接触时间对效率的影响。 解释了Ca2 +和OH-释放
的机制，并且用Avrami动力学模型表示Ca2 +释放。 陶粒也用于处理含磷和铜, 锰, 铅等重
金属离子的废水。

* 试验装置, 材料和方法
** 试验装置
- 超纯水机(Unique-R10) -- 制备去离子水
- pH计(梅特勒FE28) -- 精确测试pH
- 鼓风干燥箱(DHG-9203A) -- 烘干玻璃仪器
- 数显水浴振荡器(SHA-A) -- 震荡静态反应
- 恒温干燥箱(华美HZQ-F100) -- 震荡静态反应

** 以及药剂的配置
EDTA二钠的配置: 称取12.0212gEDTA二钠(AR),
- EDTA二钠 2 ----
- 钙羧酸
- 20%氢氧化钠
- 1%氢氧化钠
- 盐酸
- 钙标准溶液

** DONE 陶粒的来源
陶粒是由石灰泥，粉煤灰和一些添加剂（硅藻土，锯末，高岭土）制成的。石灰泥是从江苏
省新大纸业有限公司的碱回收过程. 粉煤灰取自南京某热电厂. 并示于表1中。石灰泥被用
作氧化钙的来源并且还用作成孔材料。粉煤灰含有大量的SiO 2（53.54重量％）和Al 2 O 3（28.80重量％）。当粉煤灰用作烧结陶粒的原料时，它可以弥补石灰泥的缺点。木质素是木屑的重要组成部分。
** TODO 试验材料 :等XRD出来:
皆为分析纯
*** 动态释出
**** 反应器参数
内径\[d=6cm\], 高\[h60cm\]. 滤料填充率60%. 水力停留时间:
\[t = \frac{V}{u}\] = 15h
- u: 44.08ml/h
- V: \[V = (d/2)^{2} \times \pi \times h = 655.632ml\]
- t: 水力停留时间
** TODO 实验方法 :最后一组时间:
*** 静态释出
通过使200mL去离子水在250mL锥形瓶中与陶粒（1, 2, 3, 4, 5g）反应，进行批量实验以研究
陶粒中Ca 2+和OH的释放。将烧瓶在预定温度（25℃）下浸入水浴（型号SHZ-82）中，然后以
120r/min摇动。使用1%NaOH和10%HNO3溶液调节初始pH（2, 4, 9）。以预定间隔（0.5, 1,
2, 3, 6, 8, 10, 12, 16, 20, 24, 28, 40, 52, 64, 88, 136, 192小时）取水样，TODO
*** 动态释出

* 结果和讨论
** 陶粒的性质
表3显示了陶粒的物理和化学性质，例如表观密度，24小时吸水率，表观孔隙率，圆柱体压缩强度和可用石灰含量。通过比较，可以注意到陶粒LFS（50wt％石灰泥+ 45wt％粉煤灰+ 5wt％锯末）和LFSK（50wt％石灰泥+ 40wt％粉煤灰+ 5wt％锯末+）的24小时吸水率和表观孔隙率5wt％高岭土）高于陶粒LF（40wt％石灰泥+ 60wt％粉煤灰）和LFD（40wt％石灰泥+ 55wt％粉煤灰+ 5wt％硅藻土）。在1050℃下烧结2小时后，锯末中的木质素被烧掉，因此木屑的添加增加了陶粒中用于吸水的可用空间。对于陶粒，有一种趋势是较高的水吸附和孔隙率可以显着降低密度和抗压强度（Zou等，2009; Huang等，2005）。陶粒的性质符合这一趋势。陶粒的XRD图谱如图1所示。钙钛矿（CaAl2Si2O8），钙黄长石（Ca2Al2SiO7），硅灰石（CaSiO3）和石英（SiO2）被观察为主要晶相，这是由烧结过程中的固态反应产生的。 。有人提出低温制造（Qin et al。，2015）和Na和K等杂质的存在会降低钙长石和钙黄长石的晶体结构稳定性。结果，在这项研究中，钙长石和钙黄长石的一部分可能会不一致地溶解，如方程式1所示。 （2）和（3）（Shen等，1993）。此外，可利用的石灰和水之间的反应也带来更多的Ca 2+和OH-释放，如公式1所示。 （4）。因此，这些结晶相的存在确保了从制备的陶粒中释放出Ca 2+和OH-。

** 对比新4号和L60滤料的性能
** 单因素试验结果及分析
** 多孔硅酸钙水合物的磷回收性能
\setlength{\parindent}{1.0cm}
反应时间对抑制磷浓度的影响如图1所示。在最初的20分钟内观察到磷浓度急剧下降。随着时间的延长，磷浓度略有下降。当反应在60分钟达到平衡时，抑制磷浓度的差异是显着的。当Ca/Si摩尔比为0.6时，抑制磷浓度达到22.19mg/L。随着Ca/Si摩尔比的增加，样品的除磷能力显着提高。当Ca/Si摩尔比为2.2时，抑制磷浓度为2.16mg/L。
\par

\setlength{\parindent}{1.0cm}
图2显示了不同样品投加的磷去除。当剂量增加时，磷去除效率提高，并且在4000mg/L时获
得最高的去除效率。然后，随着样品剂量的进一步增加，除磷效率几乎保持稳定。相比较而
言，CSH: Ca/Si = 2.2显示出最高的除磷效率。限制磷浓度仅为2.16mg/L，沉积物质量为
3750mg。但是，CSH: Ca/Si = 2.2的磷含量仅为2.6%。由于磷的去除循环，样品的磷含量可以增加。
\par


----------------------------

\begin{figure}
    \centering
    \begin{minipage}{0.45\textwidth}
        \centering
        \includegraphics[width=0.9\textwidth]{fig.1.png} % first figure itself
        \caption{反应时间对抑制磷浓度的影响}
    \end{minipage}\hfill
    \begin{minipage}{0.45\textwidth}
        \centering
        \includegraphics[width=0.9\textwidth]{fig.2.png} % second figure itself
        \caption{样品用量对抑制磷浓度的影响}
    \end{minipage}
\end{figure}


\includegraphics[width=0.9\textwidth]{fig.3.png}
\captionof{figure}{除磷循环抑制磷浓度的变化} \label{tab:title}

--------------------------------



\setlength{\parindent}{1.0cm}
从除去的合成溶液中分离样品，然后加入初始磷浓度为100mg/L的合成溶液中。抑制磷浓度
的变化如图3所示。CSH的除磷性能: Ca/Si = 2.2在前3次保持良好，在第12次后停止。
CSH: Ca/Si = 2.2的磷含量为14.10%，而CSH: Ca/Si = 1.6的磷含量达到18.64%。CSH:与
CSH相比，Ca/Si = 1.6具有更高的磷回收性能: Ca/Si = 2.2.样品的磷去除性能与pH值有关。随着磷去除时间的延长，pH值降低(图4)。如图所示，CSH: Ca/Si = 2.2在前3次引起一系列高pH值(pH = 9.8 10.2)，并在第4次(pH = 8.5)急剧下降。CSH: Ca/Si = 1.6可以长时间保持高pH值(pH = 8.5-9.5)(去除磷的10倍)。这种条件有利于除磷循环。
\par

** 多孔硅酸钙水合物的孔结构
\setlength{\parindent}{1.0cm}
样品上的氮吸附 - 解吸等温线如图5所示。结果表明吸附滞后环现象。这意味着样品上存
在中孔或窄间隙孔cite:Poreestructure_and_surface_fractal_characteristics_of_calcium_silicate_hydrates_contained_organic_macromolecule。在mespore中的吸附主要发生在中压区域(0:4op = p0o0:9).
随着Ca/Si摩尔比的增加，吸附磁滞回线现象变得明显，吸附曲线增大。CSH的比表面积:
Ca/Si = 0.6，CSH: Ca/Si = 1.0，CSH: Ca/Si = 1.6，CSH: Ca/Si = 2.2和雪硅
钙石分别为11.91, 59.67, 113.36, 121.03和49.85m2/g，分别。这些样品的孔体积相应
地为0.07,0.30,0.52,0.65和0.15cm 3/g。Ca/Si摩尔比的增加导致孔径更小，比表面积和孔体积更大。
\par

\setlength{\parindent}{1.0cm}
通过FESEM观察和EDS分析检查了雪硅钙石的表面结构，CSH: Ca/Si = 1.6和CSH: Ca/Si =
2.2(图6)。与雪硅钙石相比，CSH: Ca/Si = 1.6具有正面的纤维网络结构，具有大量的中孔。
CSH: Ca/Si = 2.2除了纤维网络结构外还有大块的片状晶体。EDS分析证实，雪硅钙石的粗糙
表面，CSH: Ca/Si = 1.6和CSH: Ca/Si = 2.2主要由Ca和Si组成。Ca/Si摩尔比分别为0.8,1.5
和2.0。由于在过滤浆料时部分Ca^{2+}的损失，合成后材料的Ca/Si摩尔比降低。因此，CSH的单一除磷效率随着比表面积的增加而增加。
\par

---------------------------

\begin{figure}
    \centering
    \begin{minipage}{0.45\textwidth}
        \centering
        \includegraphics[width=0.9\textwidth]{fig.4.png} % first figure itself
        \caption{除磷循环对pH值的影响}
    \end{minipage}\hfill
    \begin{minipage}{0.45\textwidth}
        \centering
        \includegraphics[width=0.9\textwidth]{fig.5.png} % second figure itself
        \caption{样品上的氮吸附 - 解吸等温线。}
    \end{minipage}
\end{figure}



\includegraphics[width=0.9\textwidth]{fig.6.png}
\captionof{figure}{FESEM观察和EDS分析} \label{tab:title}

(a)雪硅钙石表面;
(b)雪硅钙石的化学分析;
(c)CSH表面: Ca/Si = 1.6;
(d)CSH的化学分析: Ca/Si = 1.6;
(e)CSH表面: Ca/Si = 2.2;
(f)CSH的化学分析:Ca/Si = 2.2;

--------------------------------------------

** Ca^{2+}释放动力学
\setlength{\parindent}{1.0cm}
实验表明，Ca^{2+}浓度随着Ca/Si摩尔比的增加而增加(图7)。从雪硅钙石释放的
Ca^{2+}浓度，CSH: Ca/Si = 1.6和CSH: Ca/Si = 2.2分别为2.10, 3.56, 4.91mg/g。
根据Avrami动力学模型方程(方程(2)绘制Ca^{2+}释放的实验能力)。cite:demirkıran07_dissol_kinet_ulexit_perch_acid_solut
\par

\[-\ln(1-x) = kt^{n} \ \ \ (2)\]

\setlength{\parindent}{1.0cm}
其中k是动力学常数，n是固体的特征常数，t是反应时间(min)和x(x¼Ct/ C_{max}，Ct是时间t的浓度(mg/L)，C_{max}是最大浓度(mg)/L))是分数转换。特征常数n为0.9019。通过将Avrami动力学模型拟合到从图6(表2)获得的实验数据来确定动力学常数。高相关系数(R2> 0.99)表明该模型可以很好地描述Ca^{2+}释放规律。
\par


\setlength{\parindent}{1.0cm}
如表2所示，随着Ca/Si摩尔比的增加，k变大。结合材料的比表面积(S)，可以建立k和S之间的关系(方程(3))。
\par

\[k = 0.022S^{0.292} \ \ R = 0.9135 \ \ \ (3)\]

\setlength{\parindent}{1.0cm}
根据方程(3)样品的比表面积和Ca^{2+}释放速率相互吻合良好。通过用方程(3)代替，得到比表面积与Ca^{2+}溶解浓度之间的关系进入方程(2)。
\par

\[-\ln(1-x) = 0.022S^{0.292}t^{0.9019} \ \ \ (4)\]

\setlength{\parindent}{1.0cm}
根据方程(4)，Ca^{2+}释放浓度与比表面积有关。该结果证明了Ca/Si摩尔比对磷回收能力的影响。Ca/Si摩尔比影响孔结构和Ca^{2+}释放能力。由于比表面积较大，Ca^{2+}释放得更快。多孔结构提供了维持高浓度Ca{2+}释放的局部条件。比较CSH: Ca/Si = 1.6与CSH: Ca/Si = 2.2，前者具有较高的磷回收性能。因此，Ca^{2+}释放规律是磷回收性能的关键。CSH: Ca/Si = 1.6可以释放适当浓度的Ca^{2+}和OH^{-}以维持pH值在8.5-9.5之间。磷酸盐以这些pH值范围内的HPO^{2-}_{4}形式存在.cite:liu12_remov_high_concen_phosp_by_calcit Ca^{2+}，OH^{-}和HPO^{2-}_{4}形成高浓度的局部条件。这种条件(pH = 8.5-9.5)有利于羟基磷灰石的形成。
\par

\setlength{\parindent}{1.0cm}
可以通过XRD进一步研究该机理。比较样品的XRD图谱(图8)。当Ca/Si摩尔比为0.6:1和1:1时，
生产硬硅钙石(PDF卡23 0125，化学式Ca_{6}Si_{6}O_{17}(OH)_{2})。对于CSH: Ca/Si =
0.6，SiO 2的主峰出现在20.3051和21.5621。CSH中的主峰: Ca/Si = 1.6和CSH: Ca/Si = 2.2
归属于jennite(PDF卡18-1206;式Ca_{9}Si_{6}O_{18}(OH)_{6}·8H_{2}O;理论Ca/Si摩尔比
为1.5)。CSH: Ca/Si = 2.2的XRD图谱显示存在Ca(OH)_{2}。形成的Ca(OH)_{2}的覆盖率与基于FESEM观察的结果完全一致[27]。
\par

\begin{figure}
    \centering
    \begin{minipage}{0.45\textwidth}
        \centering
        \includegraphics[width=0.9\textwidth]{fig.7.png} % first figure itself
        \caption{样品中释放的Ca^{2+}浓度}
    \end{minipage}\hfill
    \begin{minipage}{0.45\textwidth}
        \centering
        \includegraphics[width=0.9\textwidth]{fig.8.png} % second figure itself
        \caption{样品的X射线衍射(XRD)图案。}
    \end{minipage}
\end{figure}

\setlength{\parindent}{1.0cm}
实验表明，与硬硅钙石和雪硅钙石相比，jennite具有更强的Ca^{2+}释放能力。低Ca/Si
摩尔比导致白炭黑过剩。因此，在材料表面上形成富含Si的层并阻止Ca^{2+}释放。随后,
材料的磷回收能力下降。Ca(OH)_{2}的形成是由于具有高Ca/Si摩尔比的碳化物残余物的
过剩。由于Ca(OH)_{2}的存在，CSH的单磷去除效率: Ca/Si = 2.2优于其他样品。然而,
大量的Ca^{2+}被释放并与浸入合成溶液中的材料一样快地与磷酸根离子反应。羟基磷灰石层在短时间内形成并导致孔结构的阻塞。因此Ca^{2+}释放能力下降。
\par

* 总结
通过1050℃的固态反应，石灰泥和粉煤灰在陶粒生产中成功回收。对制备的陶粒的性质，结
晶相和微观结构进行了表征。 在批量实验的基础上，研究了配方，用量，温度，初始pH和
接触时间对陶粒中Ca2 +和OH-释放的影响。 由其他组员评估了陶粒的磷和铜离子去除性能。
从该研究中推导出以下具体结论。
** 变量
\[Ca^{2+}\]和\[OH^{-}\]从陶粒中释放出来，主要是由于钙长石，钙黄长石和剩余由氧化
 钙组成的石灰来溶解。 与钙长石相比，钙黄长石具有更强的\[Ca^{2+}\]和OH-释放能力。
 Avrami动力学模型很好地拟合了\[Ca^{2+}\]释放。 孔隙率，剂量, pH的改变与\[Ca^{2+}\]浓度的增加有关

** 陶粒具有改变水溶液pH的强大能力
值得注意的是，在各种条件下, 它们仍然可以（pH = 9.3-10.9）保持水溶液在碱性条件下，并且\[Ca^{2+}\]的释放不受影响。
*** TODO 在酸性条件下
*** TODO 在碱性条件下

