#+TITLE: 1508032018-陈力-造纸白泥(lime mud)滤料-供碱释钙－文献综述
#+latex_header: \usepackage{float}
#+LATEX_HEADER: \usepackage[UTF8]{ctex}
#+LATEX_HEADER: \setCJKmainfont{Sarasa Mono T CL}


* 绪论

** 概述
纸浆由木浆或植物纤维构成，主要用于书面交流。最早的纸是纸莎草纸，由古埃及人的芦苇
制成。纸张是由中国人在二世纪制作的，可能是由一位名叫蔡伦的中国宫廷官员制作的。他
的论文是用树皮和旧鱼网制成的。几乎立即被认为是一个有价值的秘密，它是在日本人获得
该方法知识之前的500年。从公元8世纪末开始，造纸业在伊斯兰世界闻名。造纸知识最终向
西移动，第一家欧洲造纸厂于1150年左右在西班牙瓦伦西亚的Jativa建造。 15世纪，造纸
厂存在于意大利，法国，德国和英国，到16世纪末，纸张正在整个欧洲制造。无论是在现代
工厂生产还是通过最细致，最精细的手工方法生产的纸张都由连接纤维组成。纤维可以来自
许多来源，包括布抹布，来自植物的纤维素纤维，最值得注意的是树木。在此过程中使用布
料始终生产出高质量的纸张。今天，大量的棉和亚麻纤维混合在一起，创造了许多特殊用途
的优质纸张，从婚礼邀请纸库存到专用纸笔和墨水图纸。制造纸张的方法基本上是一个简单
的方法 - 混合植物纤维，并在热水中煮，直到纤维柔软但不溶解。热水还含有碱性化学物
质，例如碱液，它们在烹饪时软化纤维。然后，使筛网状材料通过混合物，让水滴落和/或
蒸发，然后挤压或吸去额外的水。留下一层纸。对于该过程必不可少的是纤维，其从未被完
全破坏，并且当混合和软化时，在纸本身内形成交错图案。


** 中国古代
自公元前8世纪以来，大麻纸已在中国用于包装和填充
cite:Needham_Joseph_1986_Science_and_Civilization_in_China 。中文着作清晰的论文发表于公元
前8年，cite:World_Archaeological_Congress_eNewsletter 。传统的发明者归属于汉伦(公元前202年 - 公元前220年)的宫廷官员蔡伦，
据说发明了大约公元105年的纸张使用桑树和其他韧皮纤维以及渔网，旧抹布和麻废物。cite:In_Encyclopædia_Britannica
用作书写媒介的纸张在3世纪已经普及cite:Science_and_Civilization_in_China ，到了6世纪，卫生纸也开始在中国使用。[5]在唐
朝(公元618 - 907年)，纸被折叠并缝制成方形袋以保存茶的味道，cite:Needham_Joseph_1986_Science_and_Civilization_in_China 而后来的宋朝(公
元960-1279)是第一个发行纸币的政府。

** 伊斯兰
在8世纪，造纸业扩展到伊斯兰世界，在这里，工艺得到了改进，机械设计用于批量生产。
生产开始于撒马尔罕，巴格达，大马士革，开罗，摩洛哥，然后是穆斯林西班牙。
cite:Mahdavi_2003 在巴
格达，造纸业在Grand Vizier Ja'far ibn Yahya的监督下进行。穆斯林发明了一种制作较
厚纸张的方法。这项创新帮助将造纸从艺术转变为主要产业。
cite:a_study_of_the_ancient_craft,Mahdavi_2003  最早在纸张生产中使
用水力磨坊，特别是使用纸浆厂制备造纸纸浆，可追溯到8世纪撒马尔罕。造纸厂最早的
参考文献也来自中世纪的伊斯兰世界，它们在9世纪由大马士革的阿拉伯地理学家首次提到。

** 亚洲
亚洲的传统造纸使用植物的内树皮纤维。将该纤维浸泡，煮熟，冲洗并传统地手工打浆以形
成纸浆。长纤维被分层以形成坚固的半透明纸张。在东亚，三种传统纤维是蕉麻，kozo和
gampi。在喜马拉雅山脉，纸张是由lokta植物制成的。今天，这篇论文被用于书法，印
刷，书籍艺术和包括折纸在内的立体作品。

** 欧洲与现代造纸
在欧洲，开发了使用金属线的造纸模具，水印等特征在公元1300年就已确立，而大麻和亚麻
布是纸浆的主要来源，棉花最终在南方种植园大量生产后接管。由于没有纸莎草纸和
羊皮纸的许多优点，造纸最初在欧洲并不流行。直到15世纪，随着可移动式印刷的发明及其
对纸张的需求，许多造纸厂才进入生产，造纸业成为一个产业。

随着Fourdrinier机器的发展，现代造纸始于19世纪初的欧洲。该机器可生成连续卷纸而非
单张纸。这些机器很大。有些生产纸张长150米，宽10米。他们可以100公里/小时的速度生
产纸张。 1844年，加拿大人Charles Fenerty和德国F.G.凯勒发明了机器和相关工艺，以便
在造纸中利用木浆。这项创新结束了近2000年的碎纸屑使用，开启了新闻纸生产的新纪
元，最终几乎所有纸张都是用纸浆制成的。

现代造纸方法虽然比旧方法复杂得多，但却是发展方面的改进而不是全新的造纸方法。

** 原料
大多数纸张是通过机械或化学过程制成的。大麻和黄麻纤维通常用于纺织品和绳索制造，但
它们也可用于纸张。一些高档卷烟纸是由亚麻制成的。棉麻布用于精美级别的纸张，如信头
纸和简历纸，以及纸币和安全证书。破布通常是纺织品和服装厂的切割和废料。在造纸厂使
用之前，必须将抹布切割并清洗，煮沸和打浆。用于造纸的其他材料包括漂白剂和染料，填
料如白泥(lime mud)或氧化钛，以及诸如松香，树胶和淀粉的胶料。

* 现代纸浆的组成
化学纸浆厂，生产许多不同的废物流，可大致分为有机和无机残留物，主要无机固体残余物包括绿液渣，，各种石灰残渣，回收锅炉飞灰和在二氧化氯
发生器中产生的盐饼。在这些残留物中，除了倍半硫酸盐之外的所有残留物都或多或少是碱性
的。目前在工厂区域外只使用了一小部分这些残留物：填埋场处理和工厂
的再利用是最常用的方法。由于环境和经济原因，未来应该改善这种情况。cite:Kinnarinen_2016

* 白泥(lime mud)的定义
造纸 白泥 (Limemud)是造 纸工业 中的一种副产品，来源于碱 回收过程 中的苛化反应0 ，其主要化学成分是碳酸钙 ，具有较高碱性 ，pH值介于 9．7～13．5，且存在 cr、Mn、Fe等碱性金 属[2-4]，因此被认为是一种有害的固体废弃物 。目前我国每年产生的白泥多达 1000万 t，这些白泥中只有少部分 得到利用。绝大多数企业将 白泥堆放或填埋 ，不但占用了土地资源，还会对土壤、地下水造成污染 ，也浪费了白泥中大量的资源。cite:Application_ofLim_eM_ud_forPreparation_ofCeram_sites

白泥(lime mud)是造纸工业中碱回收过程的苛化反应过程中产生的一种废物。白泥(lime mud)和粉煤灰被重新
用作原料，通过固态反应制造钙长石陶瓷。烧结温度和白泥(lime mud)含量均影响制备的陶瓷中的结
晶相。钙长石是所有样品中的主要相(样品L36，L40，L50和L60)，并且在样品L36(含有
36wt％白泥(lime mud))中显着。结果还表明，钙钛矿陶瓷可以在低烧结温度(1100℃)下合成。在
具有较高钙(高于40wt％白泥(lime mud))或较低烧结温度的样品中形成钙黄长石和硅灰石。测量体
积密度，吸水性和抗压强度。这些陶瓷重量轻，吸水率高。回收白泥(lime mud)和粉煤灰作为钙长石
陶瓷的原料是解决固体废物的可行方法。 cite:qin15_recyc_lime_mud_fly_ash

白泥(lime mud)是苛化的固体副产物，在石灰窑中再生。其中一部分作为GLD过滤器中的预涂层从工
艺中移除。白泥(lime mud)的pH值变化，并且通常与GLD的pH值相同(
cite:sthiannopkao09_utiliz_pulp_paper_indus_wastes)。


* 白泥(lime mud)的性质
洗涤和干燥后的白泥(lime mud)是粗碳酸盐的重要来源，由于其化学性质和天然潜力，可以在造纸工业中用作涂布纸中的填料，具有以下优异性能： 去除了一些化学成
分和渣滓。亮度适合造纸。随着时间的增加，白泥(lime mud)颗粒尺寸变小，2μm(15.0％)的百
分比逐渐增加，达到71.7％，因此成为更适合造纸的碳酸盐。cite:article


#+BEGIN_EXPORT latex
\nocite{poykio14_evaluat_bio_acces_non_proces, maekitalo14_charac_green_liquor_dregs_poten, jia13_use_amend_tailin_as_mine_waste_cover
, jia14_metal_mobil_tailin_cover_with, edmondson14_urban_cultiv_allot_maint_soil, buruberri15_prepar_clink_from_paper_pulp_indus_wastes,
 brunelle15_evaluat_impac_risin_fertil_prices_crop_yield, andreola11_model_simul_analy_react_system,
  ragnvaldsson14_novel_method_reduc_acid_mine, zhang15_lime_mud_from_paper_proces, zhang14_anaer_diges_food_waste_stabil}
#+END_EXPORT

熔炼物从回收锅炉中溶解可视为重新苛化过程的起点。为了避免化学品的损失，特别是钠，
从白泥(lime mud)和绿液渣洗涤液中获得的弱洗涤液被送入溶解器中。在这个阶段，钠是可溶的
Na2CO3，并且大部分硫是还原形式的可溶性硫化钠Na2S，它是一种有效的蒸煮化学品，因此
不应受到再苛化过程的影响(cite:Handbook_of_pulp )。苛化过程中的主要反应是将绿液中的Na 2 CO
3含量转化为NaOH。在苛化工厂中发生的所有重要反应都是众所周知的，
并且已经在无数的文献资料中呈现。主要反应是将碳酸钠转化为氢氧化物，需要大量的可溶性氢氧化物，这
是通过在石灰窑中煅烧白泥(lime mud)(CaCO_{3})以产生CaO而获得的，其随后根据等式1转化。
在消化器中用绿液对Ca(OH)_{2}进行初始化，其中苛化反应初始化：

GLD中的主要固体化合物是碳酸钙CaCO3，氢氧化镁Mg(OH)_{2}，碳和金属硫化物，
尤其是FeS(cite:maekitalo14_charac_green_liquor_dregs_poten )。液相含有碱性化合物，例如Na_{2}CO_{3}
和NaOH，它们负责高pH。从经济角度来看，重要的是通过GLD洗涤回收这些碱性化合物。cite:Kinnarinen_2016

两种主要的石灰窑残余物以浆液形式存在，如白泥和石灰渣。这些残留物均由CaCO_{3}，CaO
和各种杂质组成。以前的研究通常只关注白泥，在某种程度上只关注废渣。
根据Martins等人的矿物学特征，CaCO3占白泥中约90％的矿物相。还存在
二水合物形式的石膏(<4w-％)CaSO 4·2H 2 O.然而，在大多数工厂中，白泥中的碳酸钙
含量似乎高于90％。报告CaCO3含量为92-95 w-％，
将上限扩展到97 w-％，还列出了其他元素，如Mg，Si，Al，Fe，P，Na，K，和S，以少量的
各种形式存在。 Martins等人。报道，与白泥不同，废渣含有大量的
Ca2SiO4(几乎30w-％)，CaNa2(CO3)2·2H2O(约20-30w-％)，Ca(OH)2(12％) )，
以及2-4％的Mg(OH)^{2}。如上所述，在GLD的情况下，高百分比的含Si和Na的矿物相并不意
味着Si和Na实际上以成比例的高量存在。cite:Kinnarinen_2016

在苛化反应之后，必须将形成的白泥与白液分离，回收碱，分离潜在的杂质，并使石灰窑
能够高效运行。为了保持白泥的质量，从回收循环中去除NPE是重要的，这对于白泥(lime mud)分离装置和石灰窑的无故障运行是必需的。
此外，石灰窑的硫(TRS)排放可以通过白泥洗涤减少。沉淀和过滤
最常用于此阶段。脱水的白泥可以用例如干燥的方法干燥。在送往石灰窑之前使用闪蒸泥
浆干燥机。 4.2.1。白泥(lime mud)的分离熟化和苛化过程中的条件对白泥(lime mud)的分离有影响。温度，石灰用量，搅拌器速度
和停留时间等因素会影响石灰残渣的分离

* 应用
－ cite:eriksson96_displ_washin_lime_mud 石灰泥的置换洗涤：拖尾效应。
－ cite:.06_soil_stabil_fores_roads_sub 使用碱性纸浆厂化学回收过程中的石灰泥废料对森林道路基层进行土壤稳定。

* 收获
这是我第一次尝试动手模仿专业论文的写作，以前虽然天天看wg21上的papers，但是却从未
思考过其排版，非常惭愧。通过这次练习，我熟练掌握了运用bibtex来管理文献，通过谷歌
学术来更为精确的定位文献。最重要的是激起了我向ISO:wg21提交proposal的勇气。

* 致谢
- [[https://www.gnu.org/software/emacs/][GNU Emacs]] -- 如果没有Emacs这个世界上最强大的编辑软件的帮助下，我无法这么快速的完成论文任务
- [[https://scholar.google.com/][Google Scholar]] -- 最好用的学术搜索网站
- \(\LaTeX\) -- linux下没有好用的排版软件，花了半天的功夫学习了下tex，因为对
  mathjax/html/katex/emacs比较熟悉，所以还是比较容易上手的。
- [[https://github.com/jkitchin/org-ref][org-ref]] -- 比起纯手写\(LaTex\), 我更喜欢先在Emacs的org-mode中完成写作与排版，
  剩下的tex格式转换交给xelatex或者pandoc等, 但是后者自带的文献
  reference功能比较薄弱，而在org-ref这个elisp包的帮助下，使用bibtex来进行文献reference从未如此简
  单！
- [[https://ctan.org/pkg/ctex?lang=en][ctex]] -- 由于tex的先天设计缺陷，其对cjk字体的支持非常不完善，所幸现在有ctex了。
- [[https://github.com/tumashu/pyim][pyim]] -- 一个Emacs中的拼音输入法，如果没有pyim， 我无法完成这篇中文论文。
- [[https://git-scm.com/][git]] -- 本文在书写中使用git来进行版本控制，虽然大部分push等操作都是通过emacs的
  magit来完成的。好处是可以回滚至任一commit， 且能备份防灾。


bibliography:papermaking.bib
bibliographystyle:alpha
